# Importation de packages

In [11]:
import geopandas as gpd
from utils import load_data_url, load_bpe

# Données

Nous importons ici les données via une api (pour les données BPE) et via l'url pour les données filosofi en utilisant les fonctions load_bpe et load_filosofi écrites dans utils.py .
Il est à noter que pour éviter de retélécharger à chaque fois, ces bases sont sauvegardées en local après le premier chargement dans un dossier data qui se cree automatiquement.

In [12]:
df_bpe = load_bpe(
    base_url="https://data.smartidf.services/api/explore/v2.1/catalog/datasets/bpe-2018/records",
    limit=100,
    data_dir="data",
    file_name="bpe.csv",
    force_reload=False
)

In [23]:
df_filo = load_data_url(
    url="https://www.insee.fr/fr/statistiques/fichier/5055909/BASE_TD_FILO_DEC_IRIS_2018.xlsx",
    header_row=4,
    data_dir="data",
    file_name="filosofi.csv",
    force_reload=False
)

In [14]:
df_pop = load_data_url(
    url="https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/demographyref-france-pop-legale-commune-arrondissement-municipal-millesime/exports/csv?lang=fr&use_labels=False",
    data_dir="data",
    header_row=0,
    file_name="population.csv",
    force_reload=False
)

In [15]:
# garder uniquement l'année 2018
df_pop2018 = df_pop[(df_pop["geo_year"] == 2018) & (df_pop["reg_code"] == 53)]

Données géospatiales de communes pour les visualisations spatiales.

In [16]:
# 1. charger données
df_geo_bretagne = gpd.read_file(
    "https://raw.githubusercontent.com/gregoiredavid/france-geojson/master/regions/bretagne/communes-bretagne.geojson"
)

## Exploration de données

## Aperçu des données

In [17]:
df_bpe.head()

,depcom,nom_com,dep,nom_dep,reg,nom_reg,dciris,an,typequ,nom,nb_equip,year,com_arm_name,dep_name,reg_name
0,71076,Chalon-sur-Saône,71,SAONE-ET-LOIRE,27,BOURGOGNE-FRANCHE-COMTE,71076_0107,2018,D201,Médecin généraliste,1,2018,Chalon-sur-Saône,Saône-et-Loire,Bourgogne-Franche-Comté
1,18033,Bourges,18,CHER,24,CENTRE-VAL DE LOIRE,18033_0101,2018,D237,Pédicure-podologue,1,2018,Bourges,Cher,Centre-Val de Loire
2,71456,Saint-Martin-en-Bresse,71,SAONE-ET-LOIRE,27,BOURGOGNE-FRANCHE-COMTE,71456,2018,C101,École maternelle,1,2018,Saint-Martin-en-Bresse,Saône-et-Loire,Bourgogne-Franche-Comté
3,82041,Cazals,82,TARN-ET-GARONNE,76,OCCITANIE,82041,2018,A208,Agence postale,1,2018,Cazals,Tarn-et-Garonne,Occitanie
4,25377,Mésandans,25,DOUBS,27,BOURGOGNE-FRANCHE-COMTE,25377,2018,B309,Droguerie quincaillerie bricolage,1,2018,Mésandans,Doubs,Bourgogne-Franche-Comté

In [24]:
df_filo.head()

,IRIS,Libellé de l'IRIS,Commune ou ARM,Libellé commune ou ARM,Part des ménages fiscaux imposés (%),Taux de bas revenus déclarés au seuil de 60 % (%),1er quartile (€),Médiane (€),3e quartile (€),Écart inter-quartile rapporté à la médiane,...,Rapport interdécile D9/D1,S80/S20,Indice de Gini,Part des revenus d’activité (%),dont part des salaires et traitements (%),dont part des indemnités de chômage (%),dont part des revenus des activités non salariées (%),"Part des pensions, retraites et rentes (%)",Part des autres revenus (%),Note de précaution (voir onglet seuils)
0,IRIS,LIBIRIS,COM,LIBCOM,DEC_PIMP18,DEC_TP6018,DEC_Q118,DEC_MED18,DEC_Q318,DEC_EQ18,...,DEC_RD18,DEC_S80S2018,DEC_GI18,DEC_PACT18,DEC_PTSA18,DEC_PCHO18,DEC_PBEN18,DEC_PPEN18,DEC_PAUT18,DEC_NOTE18
1,010040101,Les Perouses-Triangle d'Activité,01004,Ambérieu-en-Bugey,45.4,31,11150,18540,25900,0.8,...,6.2,7.2,0.332,68.9,63.2,3.1,2.6,27.3,3.8,0
2,010040102,Longeray-Gare,01004,Ambérieu-en-Bugey,39.3,39.4,8890,16180,23290,0.89,...,8.3,9.8,0.366,69.6,62.9,4.5,2.2,26.9,3.5,0
3,010040201,Centre-Saint-Germain-Vareilles,01004,Ambérieu-en-Bugey,43.7,28.8,11830,18870,26560,0.78,...,5.2,7.4,0.347,67.7,60.6,3.1,4,28.3,4,0
4,010040202,Tiret-Les Allymes,01004,Ambérieu-en-Bugey,61.1,14.6,17180,24780,33280,0.65,...,4.3,7.3,0.387,62.7,57.5,2.1,3.1,21.2,16.1,0

Suppression de la première ligne de df_filo qui correspond aux codes de variables et qui ne nous aide pas particulièrement ici car nous préférons les noms plus explicites.

In [25]:
df_filo= df_filo.iloc[1:].reset_index(drop=True)
df_filo.head()

,IRIS,Libellé de l'IRIS,Commune ou ARM,Libellé commune ou ARM,Part des ménages fiscaux imposés (%),Taux de bas revenus déclarés au seuil de 60 % (%),1er quartile (€),Médiane (€),3e quartile (€),Écart inter-quartile rapporté à la médiane,...,Rapport interdécile D9/D1,S80/S20,Indice de Gini,Part des revenus d’activité (%),dont part des salaires et traitements (%),dont part des indemnités de chômage (%),dont part des revenus des activités non salariées (%),"Part des pensions, retraites et rentes (%)",Part des autres revenus (%),Note de précaution (voir onglet seuils)
0,010040101,Les Perouses-Triangle d'Activité,01004,Ambérieu-en-Bugey,45.4,31,11150,18540,25900,0.8,...,6.2,7.2,0.332,68.9,63.2,3.1,2.6,27.3,3.8,0
1,010040102,Longeray-Gare,01004,Ambérieu-en-Bugey,39.3,39.4,8890,16180,23290,0.89,...,8.3,9.8,0.366,69.6,62.9,4.5,2.2,26.9,3.5,0
2,010040201,Centre-Saint-Germain-Vareilles,01004,Ambérieu-en-Bugey,43.7,28.8,11830,18870,26560,0.78,...,5.2,7.4,0.347,67.7,60.6,3.1,4,28.3,4,0
3,010040202,Tiret-Les Allymes,01004,Ambérieu-en-Bugey,61.1,14.6,17180,24780,33280,0.65,...,4.3,7.3,0.387,62.7,57.5,2.1,3.1,21.2,16.1,0
4,010330102,Centre Ville,01033,Valserhône,41.9,25.9,12660,19590,28730,0.82,...,6.2,8.6,0.365,70.2,63.8,4.1,2.3,25.8,4,0

In [26]:
df_pop2018.head()

,reg_code,reg_name,com_arm_code,com_arm_name,com_arm_pop_mun,com_arm_pop_cap,com_arm_pop_tot,dep_code,arrdep_code,census_year,start_year,geo_year,epci_name,epci_code,dep_name
121,53,Bretagne,29182,Plouégat-Guérand,1067,18,1085,29,3,2016,2019,2018,CA Morlaix Communauté,242900835.0,Finistère
359,53,Bretagne,56210,Saint-Caradec-Trégomel,476,7,483,56,2,2016,2019,2018,CC Roi Morvan Communauté,245614417.0,Morbihan
592,53,Bretagne,29063,Goulien,433,8,441,29,4,2016,2019,2018,CC Cap Sizun - Pointe du Raz,242900629.0,Finistère
593,53,Bretagne,29206,Plounévez-Lochrist,2312,103,2415,29,3,2016,2019,2018,CC Haut-Léon Communauté,200067072.0,Finistère
594,53,Bretagne,29213,Plouzévédé,1779,43,1822,29,3,2016,2019,2018,CC du Pays de Landivisiau,242900751.0,Finistère

Du fait du filtrage de la région de brétagne, les index de cette base population ne commencent pas à 0. Donc on va remettre l'index à 0

In [30]:
df_pop2018=df_pop2018.reset_index(drop=True)
df_pop2018.head()

,reg_code,reg_name,com_arm_code,com_arm_name,com_arm_pop_mun,com_arm_pop_cap,com_arm_pop_tot,dep_code,arrdep_code,census_year,start_year,geo_year,epci_name,epci_code,dep_name
0,53,Bretagne,29182,Plouégat-Guérand,1067,18,1085,29,3,2016,2019,2018,CA Morlaix Communauté,242900835.0,Finistère
1,53,Bretagne,56210,Saint-Caradec-Trégomel,476,7,483,56,2,2016,2019,2018,CC Roi Morvan Communauté,245614417.0,Morbihan
2,53,Bretagne,29063,Goulien,433,8,441,29,4,2016,2019,2018,CC Cap Sizun - Pointe du Raz,242900629.0,Finistère
3,53,Bretagne,29206,Plounévez-Lochrist,2312,103,2415,29,3,2016,2019,2018,CC Haut-Léon Communauté,200067072.0,Finistère
4,53,Bretagne,29213,Plouzévédé,1779,43,1822,29,3,2016,2019,2018,CC du Pays de Landivisiau,242900751.0,Finistère

In [20]:
df_geo_bretagne.head()

    code             nom                                           geometry
0  56069           Groix  POLYGON ((-3.42179 47.62, -3.42301 47.62026, -...
1  56084            Hézo  POLYGON ((-2.68484 47.58999, -2.68694 47.58688...
2  56087  Île-aux-Moines  MULTIPOLYGON (((-2.85956 47.55989, -2.86089 47...
3  56088       Île-d'Arz  MULTIPOLYGON (((-2.80961 47.57826, -2.81267 47...
4  56243            Séné  MULTIPOLYGON (((-2.74349 47.62732, -2.74554 47...

In [33]:
print("Dimensions de bpe:", df_bpe.shape)
print("Variables de bpe:", df_bpe.columns)

print("Dimensions de df_filo:", df_filo.shape)
print("Variables de filosofi:",df_filo.columns)

print("Dimensions de df_geo_bretagne:", df_geo_bretagne.shape)
print("Variables de df_geo_bretagne:", df_geo_bretagne.columns)

print("Dimensions de df_pop2018:", df_pop2018.shape)
print("Variables de pop2018:", df_pop2018.columns)

Dimensions de bpe: (10000, 15)
Variables de bpe: Index(['depcom', 'nom_com', 'dep', 'nom_dep', 'reg', 'nom_reg', 'dciris', 'an',
       'typequ', 'nom', 'nb_equip', 'year', 'com_arm_name', 'dep_name',
       'reg_name'],
      dtype='str')
Dimensions de df_filo: (12395, 28)
Variables de filosofi: Index(['IRIS', 'Libellé de l'IRIS', 'Commune ou ARM', 'Libellé commune ou ARM',
       'Part des ménages fiscaux imposés (%)',
       'Taux de bas revenus déclarés au seuil de 60 % (%)', '1er quartile (€)',
       'Médiane (€)', '3e quartile (€)',
       'Écart inter-quartile rapporté à la médiane', '1er décile (€)',
       '2e décile (€)', '3e décile (€)', '4e décile (€)', '6e décile (€)',
       '7e décile (€)', '8e décile (€)', '9e décile (€)',
       'Rapport interdécile D9/D1', 'S80/S20', 'Indice de Gini',
       'Part des revenus d’activité (%)',
       'dont part des salaires et traitements (%)',
       'dont part des indemnités de chômage (%)',
       'dont part des revenus des activités non salariées (%)',
       'Part des pensions, retraites et rentes (%)',
       'Part des autres revenus (%)',
       'Note de précaution (voir onglet seuils)'],
      dtype='str')
Dimensions de df_geo_bretagne: (1232, 3)
Variables de df_geo_bretagne: Index(['code', 'nom', 'geometry'], dtype='str')
Dimensions de df_pop2018: (1232, 15)
Variables de pop2018: Index(['reg_code', 'reg_name', 'com_arm_code', 'com_arm_name',
       'com_arm_pop_mun', 'com_arm_pop_cap', 'com_arm_pop_tot', 'dep_code',
       'arrdep_code', 'census_year', 'start_year', 'geo_year', 'epci_name',
       'epci_code', 'dep_name'],
      dtype='str')

Nous avons choisi de restreindre l’analyse à la région Bretagne afin de garantir un bon compromis entre précision géographique et faisabilité computationnelle.

In [37]:
df_bpe_bretagne = df_bpe[df_bpe["reg"] == 53].copy()
print("Dimensions de df_bpe_bretagne:", df_bpe_bretagne.shape)

Dimensions de df_bpe_bretagne: (465, 15)

Le cas de la base Filosofi sera traité différemment car il n y a pas une variable indiquant le code de la région pour chaque commune.

TypeError: object of type 'method' has no len()

## Analyse des clés de jointure des bases